[metadata]
name = debsack
version = file: VERSION
author = Alwin Maier
author_email = a.maier@tu-berlin.de
description = Debsack: A framework for dataset creation from debian packages
license = GPL v3

[options]
packages = debsack, debsack.core, debsack.funsig, dwarfutils, pydebtools
install_requires =
    capstone==4.0.2
    pyelftools
    unix_ar

[options.entry_points]
console_scripts =
    debinfo = pydebtools.tools:deb_info
    funsig = debsack.funsig.tools:funsig

