[metadata]
name = bcemb
version = file: VERSION
author = Alwin Maier
author_email = a.maier@tu-berlin.de
license = GPL

[options]
packages = find:
python_requires = >=3.8
install_requires =
    click
    tqdm
    iterators
    gensim
    torch
    bert-pytorch
    debsack==0.2.2
    capstone==4.0.2
include_package_data = True

[options.package_data]
bcemb.palmtree =
    blob/PalmTree.zip
    blob/vocab
    blob/transformer.ep19

[options.entry_points]
console_scripts =
    word2vec = bcemb.word2vec.tools:cli
    instruction2vec = bcemb.instruction2vec.tools:cli
    asm2vec = bcemb.asm2vec.tools:cli
    palmtree = bcemb.palmtree.tools:cli

